Added CoreData
yevhentretiakov/Movie pull request #2
Opened 2022-10-20 10:32 UTC by yevhentretiakov

If user doesn't have internet connection, he will see the earlier fetched movies from the Core Data.

2022-10-21 05:56 UTC, Nikitax23 requested changes
надо еще подумать над реализацией

2022-10-21 05:56 UTC, Nikitax23 commented on Movie/Movie/Managers/CoreDataManager/CoreDataManager.swift
> +    func fetch<T: NSManagedObject>(_ object: T.Type,
нет смысла делать такой протокол. 
Он не универсальный. 
Ты таким образом никак, кроме как кор датой, не реализуешь этот протокол. А реализация с кор датой может быть только одна. 

Надо либо абстрагировать протокол, либо он не нужен совсем.

2022-10-21 05:56 UTC, Nikitax23 commented on Movie/Movie/Managers/CoreDataManager/CoreDataManager.swift
> +        request.predicate = predicate
нет смысла принимать предикат из-вне, в виде предиката. 
И нет смысла принимать сорт дескрипторы на входе, в виде дескрипторов. 

Ты должен иметь возможность сказать кор дате "дай мне все элементы такого типа", и тебе не надо знать, как они достаются, что такое дескрипторы , предикаты и тд. Ты так тянешь зависимости наверх.

2022-10-21 05:56 UTC, Nikitax23 commented on Movie/Movie/Managers/CoreDataManager/CoreDataManager.swift
> +    func getContext() -> NSManagedObjectContext {
то же самое с методом getContext, который в протоколе.

2022-10-21 05:56 UTC, Nikitax23 commented on Movie/Movie/Managers/CoreDataManager/DataAddable.swift
> +            let movie = Movie(context: context)
можно сделать так, чтоб контекст был по дефолту в ините твоей энтити. 
Ты выносишь всё наверх.

2022-10-21 05:56 UTC, Nikitax23 commented on Movie/Movie/Managers/CoreDataManager/DataAddable.swift
> +enum DataObject {
какой смысл в DataObject и DataAddable? 
можешь отписаться в лс

2022-10-21 05:56 UTC, Nikitax23 commented on Movie/Movie/Modules/Feed/Presenter/FeedPresenter.swift
> +    private var fetchedFromDataBase = false
не надо иметь такой флаг. Это выглядит, как костыль. Ты можешь опираться на наличие сети. 
Можно приводить модели к одному виду таким образом, что у тебя есть NetworkModel, CoreDataModel, UIModel. Таким образом, ты можешь сводить всё к UIModel (и результаты от сети, и результаты от локального хранилища). И таким образом у тебя на верхний уровень будет выходить всегда только одна модель. 

Так же могу сказать, что ты должен запросить у репозитория айтемы , и тебе неважно, откуда они придут: из локального хранилища , или из сети. Ты просто запросил у репозитория айтемы, и он сам решает, откуда тебе отдать их. 
В этом и фишка иметь репозиторий.

2022-10-21 05:56 UTC, Nikitax23 commented on Movie/Movie/Modules/Feed/Presenter/FeedPresenter.swift
> +        if fetchedFromDataBase {
то же самое

2022-10-21 05:56 UTC, Nikitax23 commented on Movie/Movie/Modules/Feed/Presenter/FeedPresenter.swift
> +        fetchMoviesFromDataBase()
ты 100 раз фетчишь из базы данных. 
Можно один раз зафетчить, привести к нужной модели, и работать потом уже с ней. 
И может быть один метод сёрч, у того же репозитория, который сам решает: откуда ему сёрчить. локально или из сети.

2022-10-21 05:56 UTC, Nikitax23 commented on Movie/Movie/Managers/NetworkManager/NetworkManager.swift
> +        URLCache.shared = URLCache(memoryCapacity: 0, diskCapacity: 0, diskPath: nil)
не совсем понял, чем тебе помогает эта строка?

2022-10-21 08:03 UTC, yevhentretiakov commented on Movie/Movie/Managers/CoreDataManager/CoreDataManager.swift
> +        request.predicate = predicate
А как тогда передать предикат, не в виде предиката и дескриптор, не в виде дескриптора?) 

NSPredicate там допустим еще как то можно передать просто строку и потом подставить в NSPredicate(format: string) и то там же разные инициализаторы есть, не только со строкой и так же для дескриптора

2022-10-21 08:54 UTC, yevhentretiakov commented on Movie/Movie/Managers/NetworkManager/NetworkManager.swift
> +        URLCache.shared = URLCache(memoryCapacity: 0, diskCapacity: 0, diskPath: nil)
Аламофаер если нет интернета тянул из кеша запросы и не возвращал ошибок, но если нет инета мне нужно тянуть из кор даты и этой строкой убрал кеширование прошлых запросов

2022-10-24 07:35 UTC, yevhentretiakov commented on Movie/Movie/Managers/CoreDataManager/CoreDataManager.swift
> +    func getContext() -> NSManagedObjectContext {
Я вот сделал чтобы контекст был по дефолту в ините 
<img width="609" alt="Screenshot 2022-10-24 at 10 33 28" src="https://user-images.githubusercontent.com/93151033/197471933-0439d369-e038-476e-a3a7-d894a409b469.png">

Но не пойму как мне его передать в этот инит иначе как только через метод getContext(), но так же я выношу его наверх?

2022-10-24 07:38 UTC, yevhentretiakov commented on Movie/Movie/Managers/CoreDataManager/CoreDataManager.swift
> +    func getContext() -> NSManagedObjectContext {
Так ну я убрал протокол, но метод этот все равно использую когда задаю в энтите дефолтный контекст при ините

<img width="609" alt="Screenshot 2022-10-24 at 10 33 28" src="https://user-images.githubusercontent.com/93151033/197471933-0439d369-e038-476e-a3a7-d894a409b469.png">

Так нормально?

2022-10-24 14:46 UTC, Nikitax23 commented on Movie/Movie/DataRepository/FeedRepository/FeedRepository.swift
> +    private func toMovieModel(_ movies: [MovieNetworkModel]) -> [MovieUIModel] {
я бы лучше эти два метода перенёс в extension `MovieUIModel`
и назвал `static func fromNetworkModel(_ model: MovieNetworkModel)`
`static func fromStoredModel(_ model: Movie)`

2022-10-24 15:10 UTC, Nikitax23 approved these changes
один важный коммент и один минорный. в остальном - молодец!

2022-10-24 15:10 UTC, Nikitax23 commented on Movie/Movie/Managers/CoreDataManager/CoreDataManager.swift
> -    static let shared = DefaultCoreDataManager()
стоит делать `private init() {}  ` для синглтонов. 
это делается для того, чтоб был только один инстанс , и было невозможно проинициализировать еще один инстанс этого класса

2022-10-24 15:11 UTC, Nikitax23 commented on Movie/Movie/Modules/Feed/Presenter/FeedPresenter.swift
> +    private var networkAvailable = true
`networkAvailable` => `isNetworkAvailable`

2022-10-25 07:05 UTC, merged